Switch from docker to containerd, revamp bin prepare, smarter exports

diff --git a/share/do b/share/do
--- a/share/do
+++ b/share/do
@@ -2,27 +2,36 @@
 
 set -e
 
-DOT=$(cd -P "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
-export DOT
-export TPL=$DOT/templates
-
-if [ ! -z "$1" ] && [ -z "$CLUSTER" ]; then
+if [ -n "$1" ] && [ -z "$CLUSTER" ]; then
   export CLUSTER="$1"
   shift
 fi
 
-export VM_HOST=$(hostname -s)
+DOT=$(cd -P "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
+TPL="${DOT}/templates"
+OUT_DIR="${PREFIX:-${HOME}}/kube/${CLUSTER}"
+VM_HOST=$(hostname -s)
 
-# shellcheck source=/dev/null
-source "$DOT/lib/log.sh"
-# shellcheck source=/dev/null
-source "$DOT/$CLUSTER-env.sh" 2>/dev/null || {
-  echo "Unkown cluster: $CLUSTER"
-  exit 1
+export DOT TPL OUT_DIR VM_HOST
+
+_load_env() {
+  for _file in $(echo "$@" | tr ' ' '\n'); do
+    if test -f "${_file}"; then
+      # shellcheck source=/dev/null
+      source "${_file}"
+      export $(<"${_file}" sed '/^[[:space:]]*$/d' | sed '/^#.*$/d' | cut -d= -f1)
+    fi
+  done
 }
 
-# shellcheck source=/dev/null
-source "$DOT/$CLUSTER-cluster.sh" 2>/dev/null || true
+test -f "${OUT_DIR}/config" || test -f "/kube/config" || {
+  echo "Could not find cluster config. Aborting!"
+  exit 1
+}
+_load_env "${OUT_DIR}/config" "/kube/config" "${OUT_DIR}/env" "/kube/env"
+
+# shellcheck source=./lib/log.sh
+source "$DOT/lib/log.sh"
 # shellcheck source=/dev/null
 source "$DOT/lib/utils.sh"
 # shellcheck source=/dev/null
@@ -32,15 +41,15 @@ if test -f "${DOT}/lib/host.${KUBE_HOST}.sh"; then
   source "${DOT}/lib/host.${KUBE_HOST}.sh"
 fi
 # shellcheck source=/dev/null
+source "$DOT/lib/prepare.sh"
+# shellcheck source=/dev/null
 source "$DOT/lib/network.sh"
 # shellcheck source=/dev/null
 source "$DOT/lib/orchestrate.sh"
 # shellcheck source=/dev/null
-source "$DOT/lib/prepare.sh"
-# shellcheck source=/dev/null
 source "$DOT/lib/provision.sh"
 # shellcheck source=/dev/null
-source "${DOT}/lib/vm.${VM_ENGINE}.sh"
+source "${DOT}/lib/vm.sh"
 # shellcheck source=/dev/null
 source "${DOT}/lib/addon.sh"
 
@@ -50,9 +59,10 @@ start() {
 
   prepare
   utils::function_exists "vm::prepare" && vm::prepare
-  orchestrate
+  orchestrate::main
 
   network::start
+  cluster::configure
   host::post
 }
 
@@ -68,20 +78,10 @@ clean() {
   stop
 
   # Clean prepare stage
-  rm -rf "${DOT:?}/bin/*"
-  rm -rf "$DOT/etc/tls/$CLUSTER"
+  rm -rf "${OUT_DIR:?}/bin/*"
 
   cluster::clean
   utils::function_exists "vm::clean" && vm::clean
-}
-
-orchestrate() {
-  orchestrate::master 0
-
-  for x in $(seq 0 $((VM_NUM_WORKERS-1))); do
-    orchestrate::worker "$x" &
-  done
-  wait
 }
 
 "$@"
